## Numerical python library

Numpy is a fundamental package for numeric computing with python.

It provides powerful ways to create,store,and/or manipulate data.

Which makes it able to seamlessly and speedingly integrate with a wide variety of database.

Panda is also built on this foundation .

We import a library using "Import" keyword.

Numpy common abbreviation is np.

In [10]:
import numpy as np

## The basics

In [29]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [24]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [25]:
# Get dimension
a.ndim

1

In [26]:
# Get shape
b.shape

(2, 3)

In [27]:
# Get type
a.dtype

dtype('int32')

In [34]:
# Get size
a.itemsize

4

In [32]:
# Get total size
a.nbytes

12

## Accessing/changing specific elements,rows,columns etc

In [35]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [36]:
# Get a specific element [r,c]
a[1,5]

13

In [37]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [44]:
a[1,5]=20
print(a)

a[:,2]= [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


* 3-d example

In [47]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
# Get specific element(work outsside in)
b[0,1,1]

4

In [50]:
# replace
b[:,1,:] =[[9,9],[8,8]]

In [51]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing different types of arrays

In [52]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [57]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [58]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [59]:
# random decimal numbers
np.random.rand(4,2)

array([[0.1818728 , 0.9241158 ],
       [0.78133498, 0.57756112],
       [0.77241709, 0.91247487],
       [0.4704537 , 0.45215058]])

In [60]:
# random integer values 
np.random.randint(7,size=(3,3))

array([[2, 6, 2],
       [0, 0, 2],
       [5, 2, 3]])

In [61]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
arr = np.array([1,2,3])
r1= np.repeat(arr,3,axis=0)
print (r1)

[1 1 1 2 2 2 3 3 3]
