### Tensor Flow

- . An open source library developed by google
- . Developed originally to run large numerical computations
- . Accepts data in the form of multidimensional arrays of higher dimensioons called TENSORS
- . Works on the basis of data flow graphs that have nodes and edges

- . Tensor is a generalization of vectors and matrices of potantially higher dimension
- . Tensors are arrays of data with different dimensions and ranks that are fed as input to the neural network.
- . Each computation in Tensor flow is represented as a Data flow graph.

### Program Elements in Tensor Flow
##### Constants-
##### Variable-allows us to add new trainable parameters to graph
##### Placeholders-allows us to feed data to a tensorflow model from outside a model
##### Session-A session is run to evaluate the nodes also known as TensorFlow runtime

#### Demo to Explain Variables, constants and Placeholders

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
# this is a variable
zero=tf.Variable(0)

In [4]:
# this is a constant
one=tf.constant(1)

In [5]:
new_value=tf.add(zero, one)

In [6]:
# variable value can be changed 
update=tf.assign(zero, new_value)

In [7]:
# uncomment using demo
# update_constant= tf.assign(zero, new_value)

In [8]:
# init_op=tf.initialize_all_variables()
init_op=tf.global_variables_initializer()

In [9]:
sess=tf.Session()

In [10]:
#initialize the variables
sess.run(init_op)

In [11]:
print(sess.run(zero))
#print(sess.run(one))

0


In [12]:
for _ in range(5):
    sess.run(update)
    print(sess.run(zero))

1
2
3
4
5


In [13]:
# string operations

In [14]:
hello=tf.constant("Hello")

In [15]:
world=tf.constant("world")

In [16]:
helloworld=tf.add(hello,world)

In [17]:
print(sess.run(helloworld))

b'Helloworld'


In [18]:
#placeholder
a=tf.placeholder(tf.float32)

In [19]:
b=a*2

In [20]:
#feeding a placeholder with scalar
result=sess.run(b,feed_dict={a:3})
#result=sess.run(b,{a:3})
print(result)

6.0


In [21]:
#feeding a placeholder with vector of rank 1
results=sess.run(b,feed_dict={a:[3,4,5]})

print(results)

[ 6.  8. 10.]


In [22]:
#feeding a placeholder with multidimmensional vector
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

result=sess.run(b,feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [23]:
sess.close()

In [55]:
#common syntax for creating session
#with tf.Session as sess:
    #result=sess.run(hello+world)
    #print(result)
    #many more lines
    #all lines will be executed within this session
    #no need of explicitly closing the session

In [25]:
#sess.run(a)

### Demo to explain the TensorFlow Programming Structure

In [26]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [27]:
graph=tf.get_default_graph()

In [28]:
graph.get_operations()

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=AddV2>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>]

In [29]:
a=tf.constant(10,name="a")

In [30]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=AddV2>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>]

In [31]:
#operations[0].node_def

In [32]:
b=tf.constant(20,name= "b")

In [33]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=AddV2>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>]

In [34]:
#c=a+b(=30)
c=tf.add(a,b,name="c")

In [35]:
c

<tf.Tensor 'c:0' shape=() dtype=int32>

In [36]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=AddV2>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=AddV2>]

In [37]:
#d = a*b=200
d=tf.multiply(a,b,name="d")

In [38]:
d

<tf.Tensor 'd:0' shape=() dtype=int32>

In [39]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=AddV2>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=AddV2>,
 <tf.Operation 'd' type=Mul>]

In [40]:
#e=c*d = 30*200=6000
e=tf.multiply(c,d,name="e")

In [41]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=AddV2>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=AddV2>,
 <tf.Operation 'd' type=Mul>,
 <tf.Operation 'e' type=Mul>]

In [42]:
sess=tf.Session()

In [43]:
print(sess.run(e))

6000


In [44]:
for op in graph.get_operations():print(op.name)

Variable/initial_value
Variable
Variable/Assign
Variable/read
Const
Add
Assign
init
Const_1
Const_2
Add_1
Placeholder
mul/y
mul
a
b
c
d
e


In [45]:
sess.close()

### Read in the census_data.csv data with pandas

In [46]:
import pandas as pd

In [49]:
census = pd.read_csv("C:\\Users\\User\\Desktop\\data_science bootcamp\\Dataset\\census_data.csv")

In [50]:
census.head()

age          workclass   education  education_num       marital_status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   
2   38            Private     HS-grad              9             Divorced   
3   53            Private        11th              7   Married-civ-spouse   
4   28            Private   Bachelors             13   Married-civ-spouse   

           occupation    relationship    race   gender  capital_gain  \
0        Adm-clerical   Not-in-family   White     Male          2174   
1     Exec-managerial         Husband   White     Male             0   
2   Handlers-cleaners   Not-in-family   White     Male             0   
3   Handlers-cleaners         Husband   Black     Male             0   
4      Prof-specialty            Wife   Black   Female             0   

   capital_loss  hours_per_week  native_country income_bracket  
0             0              40   United-States          <=50K  
1             0              13   United-States          <=50K  
2             0              40   United-States          <=50K  
3             0              40   United-States          <=50K  
4             0              40            Cuba          <=50K

##### Tensor flow cannot understand strings as labels,you need to use pandas.apply() method to apply a custom function that converts them to 0s and 1s. 


In [51]:
census['income_bracket'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [52]:
def label_fix(label):
    if label==' <=50k':
        return 0
    else:
        return 1

In [53]:
census['income_bracket'] = census['income_bracket'].apply(label_fix)

##### Perform Train Test Split on census data

In [54]:
from sklearn.model_selection import train_test_split

In [56]:
x_data = census.drop('income_bracket',axis=1)
y_labels = census['income_bracket']
X_train, X_test, y_train, y_test = train_test_split(x_data,y_labels,test_size=0.3,random_state=101)

##### Tensorflow offers an API called estimator

##### model=tf.estimator.LinearClassifier(feature_columns=feat_cols)

##### model.train(input_fn=input_func,steps=5000)

##### prepare feature columns and inputfunction

In [57]:
census.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

In [58]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [59]:
#creating the tf.feature_columns for the categorical values by using vocabulary lists or just using hash buckets

gender = tf.feature_column.categorical_columns_with_vocabulary_list("gender", ["Female", "Male"])
occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation", hash_bucket_size=1000)
marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital status", hash_bucket_size=1000)
relationship =  tf.feature_column.categorical_column_with_hash_bucket("relationship", hash_bucket_size=1000)
education =  tf.feature_column.categorical_column_with_hash_bucket("education", hash_bucket_size=1000)
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", hash_bucket_size=1000)
native_country =  tf.feature_column.categorical_column_with_hash_bucket("native_country", hash_bucket_size=1000)

AttributeError: module 'tensorflow.compat.v1.feature_column' has no attribute 'categorical_columns_with_vocabulary_list'

In [60]:
#creating the continuous feature_columns for the continuous values using numeric_column

age = tf.feature_column.numeric_column("age")
education_num = tf.feature_column.numeric_column("education_num")
capital_gain = tf.feature_column.numeric_column("capital_gain")
capital_loss = tf.feature_column.numeric_column("capital_loss")
hours_per_week = tf.feature_column.numeric_column("hours_per_week")

In [61]:
# put all these variables into a single list with the variable name feat_cols
feat_cols = [gender,occupation,marital_status,relationship,education,workclass,native_country,
             age,education_num,capital_gain,capital_loss,hours_per_week]

NameError: name 'gender' is not defined

In [62]:
#create the input function
#batch size is up to you
input_func=tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=100,num_epochs=None,shuffle=True)

ModuleNotFoundError: No module named 'keras'

In [ ]:
#create your model with tf.estimator
#create a linear classifier
model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

In [ ]:
#train your model on the data, for at least 5000 steps
model.train(input_fn=input_func,steps=5000)

In [63]:
#create a prediction input function 
pred_fn = tf.estimator.inputs.pandas_input_fn(x=X_test,batch_size=len(X_test),shuffle=False) 

ModuleNotFoundError: No module named 'keras'

In [ ]:
# use model.preict()and pass in your input function.
predictions = list(model.predict(input_fn=pred_fn))

In [64]:
predictions[0]

NameError: name 'predictions' is not defined

In [65]:
final_preds = []
for pred in predictions:
    final_preds.append(pred['class_ids'][0])

NameError: name 'predictions' is not defined

In [66]:
final_preds[:10]

[]

In [67]:
from sklearn.metrics import classification_report

In [68]:
print(classification_report(y_test,final_preds))

ValueError: Found input variables with inconsistent numbers of samples: [9769, 0]